export default {
  RelationStockUrl: 'stock/relationStock', // 关联库存
  CreateStockUrl: 'stock/createStock',         // 添加库存
  GetDockStockListUrl: 'stock/GetDockStockList', // 获取关联库存（商品）
  GetstockListUrl: 'stock/getstockList',       // 库存列表
  DeleteStockUrl: 'stock/deleteStock',         // 删除库存
  GetZoneStockListUrl: 'stock/getZoneStockList',  // 区域库存列表
  UpdateStockUrl: 'stock/updateStock',        // 修改库存列表
  CreatePwdCardUrl: 'passwordcard/CreatePreviewPasswordCard',   // 新建预览卡密
  GetRelationStockListUrl: 'stock/getRelationStockList',        // 查询已关联库存
  GetUnRelationStockListUrl: 'stock/getUnRelationStockList',    // 查询未关联库存
  DeleteRelationStockUrl: 'stock/deleteRelationStock',          // 删除关联库存
  zoneStockDeleteRelationStock: '/stock/zoneStockDeleteRelationStock',  // 区域库存删除关联库存
  GetPreviewPasswordCardUrl: 'passwordcard/GetPreviewPasswordCard',  // 预览卡密
  ImportPwdCardUrl: 'passwordcard/ImportPasswordCard',      // 导入卡密
  GetProductdetailUrl: 'product/getProductdetail', // 获取商品详情
  GetProductListUrl: 'product/getProductList', // 分页查询商品
  ShelvedProductUrl: 'product/shelvedProduct',        // 上架商品
  UnshelvedProductUrl: 'product/unShelvedProduct',     // 下架商品
  DeleteProductUrl: 'product/deleteProduct', // 删除商品
  BatchDeleteProductUrl: 'product/batchDeleteProduct', // 批量删除商品
  GetParentCategoriesUrl: 'product/GetParentCategories', // 查询父分类包括当前分类
  GetSubCategoryListUrl: 'product/getSubCategoryList',  // 获取子分类
  GetCategoryUrl: 'Product/GetCategory', // 一次性获取商品分类
  CreateProductUrl: 'product/createProduct', // 新建商品
  UpdateProductUrl: 'product/updateProduct', // 修改商品
  UpdateProductNameUrl: 'product/updateProductName', // 修改商品名称
  UpdateProductPriceUrl: 'product/updateProductPrice', // 修改商品价格
  UpdateProductNameAndPriceUrl: 'product/UpdateProductNameAndPrice', // 修改商品价格和名称
  GetTemplateListUrl: 'product/getTemplateList', // 分页查询模板
  GetProductctTplUrl: 'product/previewTemplate', // 预览模板
  GetSingleTemplateUrl: 'product/getSingleTemplate', // 查询单个模板
  GetStockAccount: '/prepaidcard/getPrepaidCardList',     // 获取直储帐号
  DeleteStockAccount: '/prepaidcard/deletePrepaidCard',     // 删除直储帐号
  BatchDeleteStockAccount: '/prepaidcard/batchDeletePrepaidCard',     // 批量删除直储帐号
  BatchUpdateStockAccount: '/prepaidcard/batchUpdatePrepaidCard',     // 批量更新直储帐号
  UpdateStockAccount: '/prepaidcard/updatePrepaidCard',     // 更新直储帐号
  AddStockAccount: '/prepaidcard/createPrepaidCard',     // 添加直储帐号
  GetStockCard: '/passwordcard/GetPasswordCardList',     // 获取卡密列表
  GetOrderList: '/Order/List',     // 获取订单列表
  GetOrderDetail: '/Order/Detail',     // 获取订单详情
  SaleUrl: 'Order/Sale', // 获取订单销售列表
  UpdatePrepaidCardUrl: '/prepaidcard/updatePrepaidCard', // 修改直储账号
  UpdateRelationStockPriority: '/stock/updateRelationStockPriority', // 修改关联库存优先级
  GetPwdCardUrl: '/passwordcard/GetPasswordCardList',     // 分页查询卡密列表
  GetFinancePage: '/Finance/GetFinancePage',         // 卡仓网财务明细
  GetSecretPriceGroupsURL: 'SecretPrice/GetSecretPriceGroups', // 密价设置-密价组列表
  SetGroupsURL: 'SecretPrice/SetGroups', // 密价设置-密价组列表-设置分组
  CleanGroupsURL: 'SecretPrice/CleanGroups', // 密价设置-密价组列表-设置分组
  GetAllSecretPriceGroupsURL: 'SecretPrice/GetAllSecretPriceGroups', // 按组给密价列表
  GetGroupsURL: 'SecretPrice/GetGroups', // 根据站点获得站点下的分组
  CreateSecretPriceGroupURL: 'SecretPrice/CreateSecretPriceGroup', // 创建密价组
  GetStatistics: '/Finance/GetStatistics', // 财务统计
  GetWithDrawDetail: '/Finance/GetWithDrawDetail', // 查看详情
  GetSingleSecretPriceGroupsURL: 'SecretPrice/GetSingleSecretPriceGroups', // 按组给密价-根据分组编号获得分组详情
  GetSecretPriceFromProductIdUrl: 'SecretPrice/GetSecretPriceFromProductId', // 跟据商品得到密价
  SetSecretPriceUrl: 'SecretPrice/SetSecretPrice', // 设置密价
  SetSecretPriceAndPriceUrl: 'SecretPrice/SetSecretPriceAndPrice', // 同时设置售价和密价
  CleanSecretPriceUrl: 'SecretPrice/CleanSecretPrice', // 清除密价
  GetDetailsFromGroupIdUrl: 'SecretPrice/GetDetailsFromGroupId', // 已密价商品
  GetWithDrawPage: '/Finance/GetWithDrawPage', // 查询提现记录
  ApplyWithDraw: '/Finance/ApplyWithDraw', // 查询提现
  GetStockDetail: '/prepaidcard/getPrepaidCardList', // 获取库存详情(查看直储账号)
  GetSupplyReviewList: '/PurchaseApply/PurchaseApplyAudit', // 供货审核列表
  DenySupply: '/PurchaseApply/DeniedSupply', // 禁止供货
  AllowSupply: '/PurchaseApply/AllowSupply', // 允许供货
  ComplaintList: '/Complaint/ReceiverComplaintList', // 获取投诉列表
  ComplaintDetail: '/Complaint/ComplaintDetail', // 获取投诉详情
  OperatorComplaint: '/Complaint/OperatorComplaint', // 处理投诉
  OperatorWaitComplaint: '/Complaint/OperatorWaitComplaint', // 处理投诉待查
  SubAccountListUrl: 'account/SubAccountList', // 获取子用户列表
  SubAccountDetailUrl: 'account/SubAccountDetail', // 获取子账户详情
  UpdateSubAccountUrl: 'account/UpdateSubAccount', // 修改编辑子账户
  LockSubAccountUrl: 'account/LockSubAccount', // 禁用子账户
  UnLockSubAccountUrl: 'account/UnLockSubAccount', // 启用子账户
  AddSubAccountUrl: 'account/AddSubAccount', // 新增子账户
  GetSubAccountPermissionListUrl: 'account/GetSubAccountPermissionList', // 获取权限列表
  SetSubAccountPermissionUrl: 'account/SetSubAccountPermission', // 获取权限列表
  GetWithDrawAmountUrl: 'Finance/GetWithDrawAmount', // 获取提现金额
  SendCodeUrl: 'Account/SendCode', // 发送短信验证码
  CreatePersonalIdentificationUrl: 'Account/CreatePersonalIdentification', // 个人认证
  CreateCompanyIdentificationUrl: 'Account/CreateCompanyIdentification', // 企业认证
  CheckLoginUrl: 'Account/CheckLogin', // 登录
  GetCurrentUrl: 'Account/GetCurrent', // 未审核获取当前用户信息
  GetAccountUrl: 'Account/GetAccount', // 获取账户信息
  GetSubAccountPermissionListExtendUrl: 'account/GetSubAccountPermissionListExtend', // 获取子账号权限列表
  LogOutUrl: 'account/LoginOut', // 退出登录
  HandleOrderUrl: '/Order/HandleOrder', // 订单处理
  UpdateIdentificationUrl: '/Account/UpdateIdentification', // 修改认证
  StasticPurchaseApplyAuditUrl: 'purchaseapply/StasticPurchaseApplyAudit', // 统计供货数量
  GetSecretPriceGroupsDealersUrl: 'SecretPrice/GetSecretPriceGroupsDealers', // 分页查询密价组进货商
  SetSecretGroupUrl: 'SecretPrice/SetSecretGroup', // 设置密价组
  StasticSecretPriceGroupUrl: 'SecretPrice/StasticSecretPriceGroup', // 统计密价组内客户数量
  DeleteSecretGroupUrl: 'SecretPrice/DeleteSecretGroup', // 删除密价组
  GetProductSecretPriceListUrl: 'SecretPrice/GetProductSecretPriceList', // 根据商品给密价分页查询
  GetSecretPriceGroupsByProductIdUrl: 'SecretPrice/GetSecretPriceGroupsByProductId', // 根据商品id获取密价组
  DeletePasswordCardUrl: 'PasswordCard/DeletePasswordCard', // 批量删除卡密
  CheckStockUrl: 'Stock/CheckStock', // 检查库存状态
  GetRelationCategoryListUrl: 'Product/GetRelationCategoryList', // 获取关联分类列表
  GetErrorPasswordCardListUrl: 'PasswordCard/GetErrorPasswordCardList', // 分页查询错卡池列表
  HandleErrorCardUrl: 'PasswordCard/HandleErrorCard', // 处理错卡
  GetStockLogListUrl: 'Stock/GetStockLogList', // 分页查询库存日志列表
};
